### PR TITLE
Check for already processed transaction

### PR DESCRIPTION
**Pull request by DarrenWestwood**
Fixes duplicate transactions when confirmation is not set to 2

### CODE REVIEW

**Comment by jusasiiv** [comment]
Nice code for fix. But placement for check prevents doing Test Setup as from first test callback onwards there will be txid `WarningThisIsAGeneratedTestPaymentAndNotARealBitcoinTransaction` in db

We could move https://github.com/blockonomics/whmcs-bitcoin-plugin/pull/78/files#diff-4d9ac2c7462a79fcb731a02afe863586R114 but need to check that using generated test txid in other places wont mess anything

**Comment by jusasiiv** [comment]
Actually thinking about this, the txid check could be moved to where the WHMCS own checkcbtrans is to keep the functionality the same

**Comment by DarrenWestwood** [comment]
> Actually thinking about this, the txid check could be moved to where the WHMCS own checkcbtrans is to keep the functionality the same

Moved in f78fbc1

**Comment by jusasiiv** [comment]
And lastly we should remove 
```
if($txid == 'WarningThisIsAGeneratedTestPaymentAndNotARealBitcoinTransaction') {
	$txid = 'WarningThisIsATestTransaction_' . md5(uniqid(rand(), true));
}
```
as now it causes the double transaction bug when making test transactions

**Comment by DarrenWestwood** [comment]
> And lastly we should remove

Updated in 375d106

**Comment by jusasiiv** [comment]
Changed the way the txid is checked 2606792b1e1ef86fb7d78ce7898e682db4093d3f

**Comment by DarrenWestwood** [comment]
> Changed the way the txid is checked [2606792](https://github.com/blockonomics/whmcs-bitcoin-plugin/commit/2606792b1e1ef86fb7d78ce7898e682db4093d3f)

Tested. The change works as desired without any issues.

**Pull request merged**
