### PR TITLE
Fix convert to for processing, issue #80

### PR DESCRIPTION
**Pull request by DarrenWestwood**
Fix convert to for processing, issue #80

Still to do:
Fix conversions if the user changes the currency on the frontend.

### CODE REVIEW

**Comment by agarzon** [comment]
I just rebases master into this PR and fix some conflicts. Deeper test and review is coming.

**Comment by agarzon** [comment]
This last commit bf11cf6 passes all my test, it takes the currency associated to the client based in the invoice (order) and compares with the one saved during the payment. So it determines if convertion is requiered (when are diferent) or not when the same currency was used during the transaction.

The only drawback is that it creates some "credits" in the user because the math is exact (your own rate with the value recieved) and ignores the rate from blocknomics or any Extra Currency Rate Margin % you could add in your settings.

I propose to do as Paypal,  they caps the transaction amount to the one that was due in the invoice so no credits are generated.

**Comment by blockonomics** [comment]
>The only drawback is that it creates some "credits" in the user because the math is exact (your own rate with the value recieved) and ignores the rate from blocknomics or any Extra Currency Rate Margin % you could add in your settings.

Can you explain this with some examples

**Comment by agarzon** [comment]
> Can you explain this with some examples

Sure, here:

### Test 1

**In WHMCS settings:**
Convert To For Processing: **NONE**
Base currency: USD
Client currency: VES
RATE: 800000
Invoice value: 100000 VES

**Blockonomics checkout page:**
0.00000859 BTC = 100000 VES
image

**Result:** 
Invoice paid: 100000 VES (100% of the amount, all perfect)

### Test 2

**In WHMCS settings:**
Convert To For Processing: **USD**
Base currency: USD
Client currency: VES
RATE: 800000
Invoice value: 100000 VES

**Blockonomics checkout page:**
0.00000859 BTC = 100000 VES (notice the BTC value is a bit higher that the previos tests, even when the invoice is the exact same value)
image

**Result:** 
Invoice paid: 104000 VES (this invoice was overpaid, generating a credit in the user of 4000 VES)

image

**Comment by blockonomics** [comment]
On checkout the USD amount to be paid should be 0.125USD . Is this caused by WHMCS rounding up * $params['amount']* to 2 decimal places when it submits to our payment gateway? If yes, then it is ok. Extra credit is not a reason of worry. 
We should check with amount like 0.124USD. If it is rounded down to 0.12USD then it will cause invoice to underpay (lets check) which is a problem

**Comment by blockonomics** [comment]
Also please sync branch with master.. the pull request diff is unnecessarily too large

**Comment by agarzon** [comment]
> Also please sync branch with master.. the pull request diff is unnecessarily too large

The changes I pushed are not part of this PR : https://github.com/blockonomics/whmcs-bitcoin-plugin/pull/93/commits

And since brach was created before the refactor, that's why the big diff.

I can only open another PR based in my changes.

**Comment by agarzon** [comment]
> On checkout the USD amount to be paid should be 0.125USD . Is this caused by WHMCS rounding up _$params['amount']_ to 2 decimal places when it submits to our payment gateway? If yes, then it is ok. Extra credit is not a reason of worry.

It makes sense, but still other gateways avoid overpay invoices.

> We should check with amount like 0.124USD. If it is rounded down to 0.12USD then it will cause invoice to underpay (lets check) which is a problem

The plugin uses the funcion round() which in effect, in your example, will round down to 0.12 (and I agree is bad)

So, we can do one of these:

- Round up with precision (so 0.124 becomes 0.13 and not 0.12). (I pushed that function anyways)
- We can increase the precision, currently all is rounding to 2 decimals. We could just use 6 decimals (example) for precision if we want to.

**Comment by blockonomics** [comment]
3685340 isn't what I was expecting. I was referring to the amount displayed in the checkout itself (rather than in the callback). In the checkout payment screen itself it should display 0.13 instead of 0.12. The BTC amount to be paid also is hence proportionately changed.

No changes would be required on callback

**Comment by blockonomics** [comment]
Was showing wrong diff. Closing here and opened new PR https://github.com/blockonomics/whmcs-bitcoin-plugin/pull/103

**Pull request closed without merging**
