### PR TITLE
Update the BCH URL structure

### PR DESCRIPTION
**Pull request by DarrenWestwood**
Issue #94

**Updates the URL structure to match Woocommerce**
- [woocommerce-plugin/php/WC_Gateway_Blockonomics.php](https://github.com/blockonomics/woocommerce-plugin/blob/master/php/WC_Gateway_Blockonomics.php#L101-L133) -> [modules/gateways/blockonomics/payment.php](https://github.com/blockonomics/whmcs-bitcoin-plugin/blob/bch-url-updates/modules/gateways/blockonomics/payment.php#L24-L62)
- [php/Blockonomics.php](https://github.com/blockonomics/woocommerce-plugin/blob/master/php/Blockonomics.php#L366-L375) -> [modules/gateways/blockonomics.php](https://github.com/blockonomics/whmcs-bitcoin-plugin/blob/bch-url-updates/modules/gateways/blockonomics.php#L244-L258)

**Updates the templates, css and js to latest versions**
- app.js
- order.css
- checkout.tpl
- crypto_options.tpl
- no_crypto_selected.tpl

### CODE REVIEW

**Comment by cnohall** [comment]
Looking forward to looking through it

**Review by cnohall — COMMENTED** [review]
Looks good, functions as expected. I've come with some comments for minor improvements.

**Comment by blockonomics** [comment]
I am getting little scared by so many changes as WHMCS is working quite well currently. This is a bit low priority. We can take this up in stages after we are done with following changes in wordpress:

- https://github.com/blockonomics/woocommerce-plugin/issues/251
- https://github.com/blockonomics/woocommerce-plugin/issues/252

**Comment by DarrenWestwood** [comment]
Closing as changes have been merged in https://github.com/blockonomics/whmcs-bitcoin-plugin/pull/141 and https://github.com/blockonomics/whmcs-bitcoin-plugin/pull/155

**Pull request closed without merging**
