### PR TITLE
Fix empty callback

### PR DESCRIPTION
**Pull request by jusasiiv**
#45

### CODE REVIEW

**Comment by blockonomics** [comment]
- Please reproduce empty callback with existing code
- Do new install and verify that empty callback is not coming with the new code

**Comment by blockonomics** [comment]
Let see see more if we can fix the issue of empty callback on first time

**Comment by jusasiiv** [comment]
>     * Please reproduce empty callback with existing code
> 
>     * Do new install and verify that empty callback is not coming with the new code


[WHMCS_callback_url_issue_report.pdf](https://github.com/blockonomics/whmcs-bitcoin-plugin/files/3367520/WHMCS_callback_url_issue_report.pdf)

**Comment by jusasiiv** [comment]
Tested on a completely fresh new install of WHMCS. Callback URL now shows up on first load of settings page, right after redirect from activating plugin.
Screenshot_2019-07-08 WHMCS - Payment Gateways(7)

**Comment by blockonomics** [comment]
Looks good. Merge pending on testing by @DarrenWestwood

**Comment by DarrenWestwood** [comment]
The fix is working for issue https://github.com/blockonomics/whmcs-bitcoin-plugin/issues/45, Callback URL displays after install:
WHMCS Callback URL - With System URL

If the WHMCS System URL is not set before the first load of the settings page, the incorrect Callback URL gets set, and cannot be changed:
WHMCS Callback URL - No System URL

**Comment by jusasiiv** [comment]
Two issues facing this PR:
1. If `new URL()` is given an invalid URL (empty SystemURL etc.) it will throw `TypeError:  is not a valid URL.`
2. If SystemURL path is invalid (using localhost, missing /whmcs part etc.) Test Setup will hang for `Failed to load resource: the server responded with a status of 404 (Not Found)`

Suggested solutions:
1. Surround with `try/catch` and on catch, show protocol error

**Comment by blockonomics** [comment]
3. Callback URl doesn't update when system URL is updated. Feel free to log a seperate issue for this or take up in same pull request as you wish

**Comment by jusasiiv** [comment]
> If SystemURL path is invalid (using localhost, missing /whmcs part etc.) Test Setup will hang for Failed to load resource: the server responded with a status of 404 (Not Found)
This was due to missing commits from master, this is already handled.

> Callback URl doesn't update when system URL is updated. Feel free to log a seperate issue for this or take up in same pull request as you wish
Due to this being possibly a larger change I will open a new issue

**Pull request merged**
